inherit_gem:
  rubocop-infinum: rubocop.yml

plugins:
  - rubocop-infinum
  - rubocop-rake

AllCops:
  TargetRubyVersion: 2.7

Rails:
  Enabled: false

Gemspec/RequiredRubyVersion:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/HashAsLastArrayItem:
  Enabled: false

Style/MissingRespondToMissing:
  Enabled: false

Style/HashTransformValues:
  Enabled: false

Style/OneClassPerFile:
  Enabled: false

Lint/ConstantDefinitionInBlock:
  Enabled: false

Performance/RegexpMatch:
  Enabled: false

RSpec/MultipleExpectations:
  Max: 5

RSpec/NestedGroups:
  Max: 5

RSpec/MultipleMemoizedHelpers:
  Enabled: false

RSpec/IndexedLet:
  Enabled: false

RSpec/ExpectInHook:
  Enabled: false

RSpec/BeEq:
  Enabled: false

RSpec/AnyInstance:
  Enabled: false

RSpec/VerifiedDoubles:
  Enabled: false

RSpec/SpecFilePathFormat:
  Enabled: false

RSpec/VoidExpect:
  Enabled: false

RSpec/NoExpectationExample:
  Enabled: false

RSpec/ReceiveMessages:
  Enabled: false

RSpec/NamedSubject:
  Enabled: false

RSpec/ContextWording:
  Enabled: false

RSpec/LeakyConstantDeclaration:
  Enabled: false
